hrmis/board/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('all',views.boards, name='boards'),
    path('add-board',views.add_board, name='add_board'),
    path('board-update/<int:pk>',views.board_update, name='board_update'),
    path('board-delete/<int:pk>',views.board_delete, name='board_delete'),
    path('board-details/<int:pk>',views.board_details, name='board_details'),

]

hrmis/hrmis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('app_settings.urls')),
    path('boards/', include('board.urls')),
    path('projects/', include('project.urls')),
    path('tasks/', include('tasks.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),name='password_reset_done'),
    path('reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),name='password_reset_confirm'),
    path('reset-password-complete', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hrmis/project/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('all',views.projects, name='projects'),
    path('project-details/<int:pk>',views.project_details, name='project_details'),
    path('create-project',views.create_project, name='create_project'),
    path('project-update/<int:pk>',views.project_update, name='project_update'),
    path('project-delete/<int:pk>',views.project_delete, name='project_delete'),
    path('gantt-chart/<int:project_id>',views.gantt_chart,name='gantt_chart')

]

hrmis/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('create-task/<int:project_id>',views.create_task, name='create_task'),
    path('task-update/<int:pk>',views.task_update, name='task_update'),
    path('task-update-for-employee/<int:pk>',views.task_update_for_employee, name='task_update_for_employee'),
    path('task-delete/<int:pk>',views.task_delete, name='task_delete'),
    path('employee-tasks/<int:employee_id>',views.employee_tasks, name='employee_tasks'),

]

hrmis/project/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=255)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-timestamp", ]

hrmis/project/forms.py
from django import forms
from . import models

class ProjectForm (forms.ModelForm):
    class Meta:
        model = models.Project
        labels = {
            'name': 'Project Name',
        }
        fields = ('name',)

hrmis/project/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import pandas as pd
from plotly.offline import plot
import plotly.express as px

from .forms import ProjectForm
from . import models
from tasks.models import Task

# Create your views here.
@login_required
def projects(request):
    template_name = 'projects.html'
    qs =  models.Project.objects.all()
    return render(request,template_name,{'obj':qs})

@login_required
def project_details(request,pk):
    template_name = 'project_details.html'
    qs =  get_object_or_404(models.Project,pk=pk)
    total = 0
    number_of_tasks = 0
    percentage_complition = 0
    for progress in qs.task_project.all():
        total = total + progress.percentage_complition
    number_of_tasks=len(qs.task_project.all())
    if number_of_tasks == 0:
        percentage_complition =0
    else:
        percentage_complition = total/ number_of_tasks
    return render(request,template_name,{'obj':qs,'percentage_complition':percentage_complition})

@login_required
def create_project(request):
    template_name = 'create_project.html'
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        print(form.errors.as_data())
        if form.is_valid():
            form.save()
            messages.success(request, 'Project successfully created.')
            return redirect('projects:projects')
    form = ProjectForm()
    return render(request, template_name, {'form': form,'type':'create'})

@login_required
def project_update(request, pk):
    template_name = 'create_project.html'
    qs = get_object_or_404(models.Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST,instance=qs)
        if form.is_valid():
            form.save()
            messages.success(request, 'Project successfully updated!')
            return redirect('projects:projects')
    else:
        context = {'form': ProjectForm(instance=qs), 'obj': qs,'type':'update'}
    return render(request, template_name, context)

@login_required
def project_delete(request, pk):
    template_name = 'project_delete.html'
    qs = get_object_or_404(models.Project, pk=pk)
    if request.method == 'POST':
        qs.delete()
        messages.success(request, 'Project has been successfully deleted!')
        return redirect('projects:projects')
    return render(request, template_name, {'obj': qs})

@login_required
def gantt_chart(request,project_id):
    qs = get_object_or_404(models.Project,pk=project_id)
    project_data = []
    for task in qs.task_project.all():
        project_data.append(
            {        
            'Task Name': task.title.title(),
            'Start Date': task.start_date,
            'End Date': task.end_date,
            'Resources': task.resource.get_full_name().title()
            } 
        )
    df = pd.DataFrame(project_data)
    fig = px.timeline(
        df, x_start="Start Date", x_end="End Date", y="Task Name", color="Resources"
    )
    fig.update_yaxes(autorange="reversed")
    gantt_plot = plot(fig, output_type="div")
    context = {'plot_div': gantt_plot,'obj':qs}
    return render(request, 'gantt_chart.html', context)

hrmis/project/templates/create_project.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{% if type == 'create' %}
Create Project
{% else %}
 Update Project with name {{obj.name|title}}
{% endif %}

{% endblock %}
{% block pagetitle %}
Add Site to Block List
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Projects</a></li>
<li class="breadcrumb-item active">
 {% if type == 'create' %}
 Create Project
{% else %}
Update Project with name {{obj.title|title}}
{% endif %}
</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <h5 class="card-title">Enter user details in the form below</h5>
 
            <!-- Horizontal Form -->
          {% if type == 'create' %}
          <form action="{% url 'projects:create_project' %}" method="POST">
          {% else %}
          <form action="{% url 'projects:project_update' obj.pk %}" method="POST">
          {% endif %}
            {% csrf_token %}
              <div class="row mb-3"> 
                <div class="col-sm-12">
                    {{ form.name|as_crispy_field }}
                </div>
           
              </div>
              <div class="text-center">
                
                <button type="submit" class="btn btn-primary">
                  {% if type == 'create' %}
                  Create Project
                  {% else %}
                  Update Project
                  {% endif %}
                
                </button>
                <a href="{% url 'projects:projects' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form><!-- End Horizontal Form -->

          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

hrmis/project/templates/gantt_chart.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}{{obj.name|title}}{% endblock %}
{% block pagetitle %}
{{obj.name|title}}
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Projects</a></li>
<li class="breadcrumb-item"><a href="{% url 'projects:project_details' obj.pk %}">{{obj.name|title}}</a></li>
<li class="breadcrumb-item active">{{obj.name|title}}</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{obj.name|title}}</h5>
          
            {% autoescape off %}
            {{ plot_div }}
           {% endautoescape %}
            
        </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

hrmis/project/templates/project_delete.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Delete {{obj.name|title}}
{% endblock %}
{% block pagetitle %}
Delete  {{obj.name|title}}
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Projects</a></li>
<li class="breadcrumb-item active">
  Delete {{obj.name|title}}
</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <h5 class="card-title">Are you sure you want to delete Project with name {{obj.name|title}}</h5>

            <!-- Horizontal Form -->
       
          <form method="POST">
        
            {% csrf_token %}
       
              <div class="text-center">
                
                <button type="submit" class="btn btn-primary">
                 Delete
     
                </button>
                <a href="{% url 'projects:projects' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form><!-- End Horizontal Form -->

          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

hrmis/project/templates/project_details.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}{{obj.name|title}}{% endblock %}
{% block pagetitle %}
{{obj.name|title}}
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'projects:projects' %}">Projects</a></li>
<li class="breadcrumb-item active">{{obj.name|title}}</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{obj.name|title}} ({{percentage_complition|floatformat:0}}% Complete) | <a href="{% url 'tasks:create_task' obj.pk  %}">Create Project Task</a></h5>
            <hr>
            <small><i class="bi bi-calendar-check"></i> Created on: {{obj.timestamp}} </small>
           
            {% if obj.task_project.all %}

            <p><a href="{% url 'projects:gantt_chart' obj.pk %}">Project Gantt Chart</a></p>
            {% endif %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            
        </div>
        </div>

      </div>
    </div>
  </section>

  <section class="section">
    <div class="row align-items-top">
      

        <!-- Default Card -->
        {% for task in  obj.task_project.all %}
        <div class="col-md-6">
        <div class="card">
          <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
              <li class="dropdown-header text-start">
                <h6>Actions</h6>
              </li>

              <li><a class="dropdown-item" href="{% url 'tasks:task_update' task.pk %}"><i class="bx bxs-pencil"></i> Update</a></li>
              <li><a class="dropdown-item" href="{% url 'tasks:task_delete' task.pk %}"><i class="bx bxs-trash"></i> Delete</a></li>
           
            </ul>
          </div>
          <div class="card-body">
              {% if task.is_past_due %}
              <h5 class="card-title" style="color: red;">          
              {% else %}
              <h5 class="card-title" style="color: green;">
              {% endif %}
              {{task.title|title}}
           
            </h5>
            <div>
              {% if task.is_past_due %}
              <span class="badge bg-danger">
                <i class="bi bi-exclamation-octagon me-1"></i>
                {% else %}
                <span class="badge bg-success">
                  <i class="bi bi-check-circle me-1"></i>
                  {% endif %}
                Start Date: {{task.start_date}}</span> - 
                {% if task.is_past_due %}
                <span class="badge bg-danger">
                  <i class="bi bi-exclamation-octagon me-1"></i>
                  {% else %}
                  <span class="badge bg-success">
                    <i class="bi bi-check-circle me-1"></i>
                    {% endif %}
                End Date: {{task.end_date}}</span>
            </div>
           <br>
            <p><strong>Status:</strong> {{task.status|title}}</p>
           <p><strong>Priority:</strong> {{task.priority|title}}</p>
           <p><strong>Resource:</strong>  {{task.resource.get_full_name|title}}</p>
           <p><strong>Date Created:</strong>  {{task.timestamp}}</p>
           <br>
           <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: {{task.percentage_complition}}%" aria-valuenow="{{task.percentage_complition}}" aria-valuemin="0" aria-valuemax="100">{{task.percentage_complition}}%</div>
          </div>
          </div>
        </div><!-- End Default Card -->
      </div>
        {% empty %}
        <h4>No tasks added</h4>
       {% endfor %}

      

    </div>
  </section>
{% endblock %}

hrmis/project/templates/projects.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Projects{% endblock %}
{% block css %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
{% endblock %}
{% block pagetitle %}
Projects
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item active">Projects</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'projects:create_project' %}">Create Project</a></h5>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    </button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
            <hr>
            <!-- Default Table -->
            <table class="table" id="project">
              <thead>
                <tr>
                  
                  <th scope="col">Name</th>
                  <th scope="col">Date</th>
                  <th scope="col">Actions</th>
              
                </tr>
              </thead>
              <tbody>
                {% for project in obj %}
                <tr>  
                    <td><a href="{% url 'projects:project_details' project.pk %}">{{project.name|title}}</a></td>
                    <td>{{project.timestamp}}</td>
                   
                    <td>
                        <a href="{% url 'projects:project_update' project.pk %}"><i class="bx bxs-pencil"></i></a>
                        <a href="{% url 'projects:project_delete' project.pk %}"><i class="bx bxs-trash"></i></a>

                    </td>
           
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        </div>

      </div>
    </div>
  </section>


{% endblock %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script>
$(document).ready(function () {
    $('#project').DataTable();
});
</script>
{% endblock %}