hrmis/board/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('all',views.boards, name='boards'),
    path('add-board',views.add_board, name='add_board'),
    path('board-update/<int:pk>',views.board_update, name='board_update'),
    path('board-delete/<int:pk>',views.board_delete, name='board_delete'),
    path('board-details/<int:pk>',views.board_details, name='board_details'),

]

hrmis/hrmis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('app_settings.urls')),
    path('boards/', include('board.urls')),
    path('projects/', include('project.urls')),
    path('tasks/', include('tasks.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),name='password_reset_done'),
    path('reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),name='password_reset_confirm'),
    path('reset-password-complete', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hrmis/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", ]

hrmis/board/forms.py
from django import forms
from . import models

class BoardForm(forms.ModelForm):
    class Meta:
        model = models.Board
        labels = {
            'title': 'Board Title',
        }

        fields = ('title','description',)

hrmis/board/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from hrmis.utils import send_board_messages

from .forms import BoardForm
from . import models

# Create your views here.
@login_required
def boards(request):
    template_name = 'boards.html'
    qs =  models.Board.objects.all()
    return render(request,template_name,{'obj':qs})

@login_required
def board_details(request,pk):
    template_name = 'board_details.html'
    qs =  get_object_or_404(models.Board,pk=pk)
    return render(request,template_name,{'obj':qs})

@login_required
def add_board(request):
    template_name = 'add_board.html'
    if request.method == 'POST':
        form = BoardForm(request.POST)
        print(form.errors.as_data())
        if form.is_valid():
            form.save()
            messages.success(request, 'Board successfully created.')
            send_board_messages(request.POST.get('title'))
            return redirect('boards:boards')
    form = BoardForm()
    return render(request, template_name, {'form': form,'type':'create'})

@login_required
def board_update(request, pk):
    template_name = 'add_board.html'
    qs = get_object_or_404(models.Board, pk=pk)
    if request.method == 'POST':
        form = BoardForm(request.POST,instance=qs)
        if form.is_valid():
            form.save()
            messages.success(request, 'Board successfully updated!')
            return redirect('boards:boards')
    else:
        context = {'form': BoardForm(instance=qs), 'obj': qs,'type':'update'}
    return render(request, template_name, context)

@login_required
def board_delete(request, pk):
    template_name = 'board_delete.html'
    qs = get_object_or_404(models.Board, pk=pk)
    if request.method == 'POST':
        qs.delete()
        messages.success(request, 'Board has been successfully deleted!')
        return redirect('boards:boards')
    return render(request, template_name, {'obj': qs})

hrmis/board/templates/add_board.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{% if type == 'create' %}
Add Site to Block List
{% else %}
Update Site for {{obj.name|title}}
{% endif %}

{% endblock %}
{% block pagetitle %}
Add Site to Block List
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'boards:boards' %}">Boards</a></li>
<li class="breadcrumb-item active">
 {% if type == 'create' %}
Add Board
{% else %}
Update Board titled {{obj.title|title}}
{% endif %}
</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <h5 class="card-title">Enter user details in the form below</h5>
 
            <!-- Horizontal Form -->
          {% if type == 'create' %}
          <form action="{% url 'boards:add_board' %}" method="POST">
          {% else %}
          <form action="{% url 'boards:board_update' obj.pk %}" method="POST">
          {% endif %}
            {% csrf_token %}
              <div class="row mb-3"> 
                <div class="col-sm-12">
                    {{ form.title|as_crispy_field }}
                </div>
                <div class="col-sm-12">
                    {{ form.description|as_crispy_field }}
                </div>
              </div>
              <div class="text-center">
                
                <button type="submit" class="btn btn-primary">
                  {% if type == 'create' %}
                  Add Board
                  {% else %}
                  Update Board
                  {% endif %}
                
                </button>
                <a href="{% url 'boards:boards' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form><!-- End Horizontal Form -->

          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

hrmis/board/templates/board_delete.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Delete {{obj.title|title}}
{% endblock %}
{% block pagetitle %}
Delete  {{obj.title|title}}
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'boards:boards' %}">Boards</a></li>
<li class="breadcrumb-item active">
  Delete {{obj.title|title}}
</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <h5 class="card-title">Are you sure you want to delete Board with title {{obj.title|title}}</h5>

            <!-- Horizontal Form -->
       
          <form method="POST">
        
            {% csrf_token %}
       
              <div class="text-center">
                
                <button type="submit" class="btn btn-primary">
                 Delete
     
                </button>
                <a href="{% url 'boards:boards' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </form><!-- End Horizontal Form -->

          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

hrmis/board/templates/board_details.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}{{obj.title|title}}{% endblock %}
{% block pagetitle %}
{{obj.title|title}}
{% endblock %}
{% block breadcrum %}
{% if request.user.is_admin %}
<li class="breadcrumb-item"><a href="{% url 'boards:boards' %}">Boards</a></li>
{% endif %}
<li class="breadcrumb-item active">{{obj.title|title}}</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{obj.title|title}}</h5>
             <p>{{obj.description|title}}</p>
        </div>
        </div>

      </div>
    </div>
  </section>

{% endblock %}

hrmis/board/templates/boards.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Boards{% endblock %}
{% block css %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
{% endblock %}
{% block pagetitle %}
Boards
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item active">Boards</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'boards:add_board' %}">Add Board</a></h5>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    </button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
            <hr>
            <!-- Default Table -->
            <table class="table" id="board">
              <thead>
                <tr>
                  
                  <th scope="col">Title</th>
                  <th scope="col">Date</th>
                  <th scope="col">Actions</th>
              
                </tr>
              </thead>
              <tbody>
                {% for board in obj %}
                <tr>  
                    <td><a href="{% url 'boards:board_details' board.pk %}">{{board.title|title}}</a></td>
                    <td>{{board.timestamp}}</td>
                   
                    <td>
                        <a href="{% url 'boards:board_update' board.pk %}"><i class="bx bxs-pencil"></i></a>
                        <a href="{% url 'boards:board_delete' board.pk %}"><i class="bx bxs-trash"></i></a>

                    </td>
           
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        </div>

      </div>
    </div>
  </section>


{% endblock %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script>
$(document).ready(function () {
    $('#board').DataTable();
});
</script>
{% endblock %}