hrmis/accounts/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login),
    path('logout', views.logout)  
]

hrmis/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.login, name='login'),
    path('redirect',views.redirect_logged,name='redirect_logged'),
    path('admin-dash',views.admin_dash,name='admin_dash'),
    path('employee-dash',views.employee_dash,name='employee_dash'),
    path('sign-up',views.sign_up,name='sign_up'),
    path('users',views.users, name='users'),
    path('users/<str:filter>',views.users, name='users'),
    path('toggle-user-status/<int:pk>',views.toggle_user_status, name='toggle_user_status'),
    path('edit-profile-admin/<int:pk>',views.edit_profile_admin, name='edit_profile_admin'),
    path('profile/<int:pk>',views.profile, name='profile'),
    path('change-password/<int:pk>',views.change_password, name='change_password'),
    
]

hrmis/board/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('all',views.boards, name='boards'),
    path('add-board',views.add_board, name='add_board'),
    path('board-update/<int:pk>',views.board_update, name='board_update'),
    path('board-delete/<int:pk>',views.board_delete, name='board_delete'),
    path('board-details/<int:pk>',views.board_details, name='board_details'),

]

hrmis/hrmis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('app_settings.urls')),
    path('boards/', include('board.urls')),
    path('projects/', include('project.urls')),
    path('tasks/', include('tasks.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),name='password_reset_done'),
    path('reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),name='password_reset_confirm'),
    path('reset-password-complete', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hrmis/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('create-task/<int:project_id>',views.create_task, name='create_task'),
    path('task-update/<int:pk>',views.task_update, name='task_update'),
    path('task-update-for-employee/<int:pk>',views.task_update_for_employee, name='task_update_for_employee'),
    path('task-delete/<int:pk>',views.task_delete, name='task_delete'),
    path('employee-tasks/<int:employee_id>',views.employee_tasks, name='employee_tasks'),

]

hrmis/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User (AbstractUser):
    DES = (('', 'Choose Designation'), ('admin', 'Admin(Organization)'),('employee', 'Employee'),)
    GENDER = (('', 'Choose Gender'),('female','Female'),('male','Male'))
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    is_admin = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    designation = models.CharField(max_length=30, choices=DES)
    email = models.EmailField(max_length=255)
    phone_number = models.CharField(max_length=255)
    gender = models.CharField(max_length=50, choices=GENDER)
    address = models.TextField()

    def __str__(self):
        return self.first_name.capitalize() + ' ' + self.last_name.capitalize() +' ('+(self.username)+')'

    class Meta:
        ordering = ["-date_joined", ]

hrmis/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.admin import widgets
from .models import User


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("email", "first_name",
                  "last_name", "designation", "gender", "address", "phone_number")


class EditProfileForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'readonly': True},),
            'designation': forms.TextInput(attrs={'readonly': True},),
        }
        fields = ("username", "email", "first_name","last_name", "designation", "gender", "address", "phone_number")

class EditProfileAdminForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'readonly': True},),
            'designation': forms.TextInput(attrs={'readonly': True},),
        }
        fields = ("username", "email", "first_name","last_name", "designation", "gender", "address", "phone_number")

hrmis/accounts/api/views.py
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)
from rest_framework.response import Response
from accounts.models import User
from hrmis.utils import Blocker, Unblocker,UnBlock
from .serializers import  loginSerializer


@csrf_exempt
@api_view(["POST"])
@permission_classes((AllowAny,))
def login(request):
    username = request.data.get("username")
    password = request.data.get("password")
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'}, status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'}, status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    Blocker()
    try:
        qs = User.objects.get(pk=token.user_id)
    except User.DoesNotExist:
        return Response({'error': 'user id does not exist'}, status=HTTP_404_NOT_FOUND)
    return Response({'token': token.key, 'user_id': token.user_id,'role':qs.designation}, status=HTTP_200_OK)

@csrf_exempt
@api_view(["GET"])
def logout(request):
    print(request.user.auth_token)
    if not request.user.auth_token:
        return Response({'error': 'something went wrong'}, status=HTTP_404_NOT_FOUND)
    request.user.auth_token.delete()
    UnBlock()
    return Response({'success': 'successfully logout'}, status=HTTP_200_OK)
    

hrmis/accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import auth
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from hrmis.utils import (
    generate_employee_id, 
    generate_password,
    send_password_and_username
    )
from . import models
from board.models import Board
from tasks.models import Task
from . import forms

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('accounts:redirect_logged')
    template_name = 'registration/login.html'
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if not user.is_active:
                messages.error(
                    request, 'Your account has been deactivate, please contact HRMIS.')
                return render(request, template_name)
            auth.login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect(reverse('accounts:redirect_logged'))
        messages.error(request, 'Invalid username or password.')
    return render(request, template_name)

@login_required
def redirect_logged(request):
    user = request.user
    if user.is_admin:
        return redirect('accounts:admin_dash')
    return redirect('accounts:employee_dash')

@login_required
def admin_dash(request):
    template_name = 'admin_dash.html'
    qs_users = models.User.objects.all()
    qs_board = Board.objects.all()
    context = {
        'admins':qs_users.filter(designation='admin').count(),
        'employees':qs_users.filter(designation='employee').count(),
        'active':qs_users.filter(is_active=True).count(),
        'in_active':qs_users.filter(is_active=False).count(),
        'total':qs_users.count(),
        'qs_board':qs_board
    }
    return render(request,template_name,context)

@login_required
def employee_dash(request):
    template_name = 'employee_dash.html'
    qs_board = Board.objects.all()
    number_of_tasks = Task.objects.filter(resource = request.user)
    context ={
        'qs_board':qs_board,
        'number_of_tasks':number_of_tasks.count()
        }
    return render(request,template_name, context)

@login_required
def users(request,filter = None):
    template_name = 'users.html'
    qs = ''
    qs_ =  models.User.objects.all().exclude(id=request.user.id)
    if filter is not None:
        qs_ =  models.User.objects.all().exclude(id=request.user.id)
        if filter == 'true':
            qs =  qs_.filter(is_active = True)
        elif filter == 'false':
            qs =  qs_.filter(is_active = False)
        else:
            qs =  qs_.filter(designation = filter)
        return render(request,template_name,{'obj':qs})
    qs =  qs_
    print('filter')
    print(filter)
    return render(request,template_name,{'obj':qs,'filter':filter})

@login_required
def sign_up(request):
    template_name = 'registration/sign_up.html'
    if request.method == 'POST':
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            gender = request.POST.get('gender')
            address = request.POST.get('address')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')
            designation = request.POST.get('designation')
            is_admin = False
            is_employee = False
            if designation == 'admin':
                is_admin = True
            else:
                is_employee = True
            employee_id=generate_employee_id()
            new_password = generate_password()
            new_user = models.User.objects.create(
                username = employee_id,
                first_name = first_name,
                last_name = last_name,
                is_admin = is_admin,
                is_employee = is_employee,
                designation = designation,
                email = email,
                phone_number = phone_number,
                gender = gender,
                address = address
            )
            if new_user.id:
                new_user.set_password(new_password)
                new_user.save()
                send_password_and_username(employee_id, email, new_password)
                messages.success(request,'User with %s has been successfully created' % (employee_id))
                return redirect('accounts:users')
    context = {
        'form':forms.SignUpForm()
    }
    return render(request,template_name, context)


@login_required
def toggle_user_status(request, pk):
    qs = get_object_or_404(models.User, pk=pk)
    print('users')
    print(qs.is_active)
    if qs.is_active == True:
        qs.is_active = False
        qs.save()
        messages.warning(request, 'Status successfully deacivated.')
        return redirect(reverse('accounts:users'))
    else:
        qs.is_active = True
        qs.save()
        messages.success(request, 'Status successfully activated.')
        return redirect(reverse('accounts:users'))

    
@login_required
def edit_profile_admin(request, pk):
    user_qs = get_object_or_404(models.User, pk=pk)
    if request.method == 'POST':
        form = forms.EditProfileAdminForm(request.POST, instance=user_qs)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile successfully updated.')
    return redirect('accounts:profile',user_qs.pk)

    
@login_required
def profile(request,pk):
    template_name = 'profile.html'
    qs = get_object_or_404(models.User,pk=pk)
    form = forms.EditProfileAdminForm(instance=qs)
    form_change_password = PasswordChangeForm(user=qs)
    context = {
        'obj':qs,
        'form':form,
        'form_change_password':form_change_password
    }
    return render (request,template_name,context)

@login_required
def change_password(request, pk):
    user_qs = get_object_or_404(models.User, pk=pk)
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=user_qs)
        print(form.errors)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password succefully changed.')
        else:
            messages.error(request, form.errors)
        return redirect('accounts:profile',user_qs.pk)

hrmis/accounts/templates/admin_dash.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Admin Dash{% endblock %}
{% block pagetitle %}
Admin Dashboard
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item active">Admin Dashboard</li>
{% endblock %}
{% block css %}
<style>
  div.hrmis-scroll {
  height: 350px;
  overflow: scroll;
}
</style>
{% endblock %}
{% block content %}
<div class="row">
  {% if messages %}
  {% for message in messages %}
  <div class="col-md-12">
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
      </button>
      {{ message }}
  </div>
</div>
  {% endfor %}
  {% endif %}
  <div class="col-lg-8">
    <div class="row">
      <div class="col-md-12">
        <h6><strong>Total Number of Users:</strong>  <span class="badge bg-primary">{{total}}</span> </h6>
      </div>
    <!-- Sales Card -->
    <div class="col-xxl-4 col-md-6">
      <div class="card info-card sales-card">

        <div class="card-body">
          <h5 class="card-title">Admins</h5>
          

          <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
              <i class="bi bi-people"></i>
            </div>
            <div class="ps-3">
              <h6><a href="{% url 'accounts:users' 'admin' %}">{{admins}}</a> </h6>
            </div>
          </div>
        </div>

      </div>
    </div><!-- End Sales Card -->

    <!-- Revenue Card -->
    <div class="col-xxl-4 col-md-6">
      <div class="card info-card revenue-card">

        <div class="card-body">
          <h5 class="card-title">Employees</h5>

          <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
              <i class="bi bi-people"></i>
            </div>
            <div class="ps-3">
              <h6><a href="{% url 'accounts:users' 'employee' %}">{{employees}}</a> </h6>
            </div>
          </div>
        </div>

      </div>
    </div><!-- End Revenue Card -->
    <div class="col-xxl-4 col-md-6">
      <div class="card info-card revenue-card">

        <div class="card-body">
          <h5 class="card-title">Active Users</h5>

          <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
              <i class="bi bi-circle-fill"></i>
            </div>
            <div class="ps-3">
              <h6><a href="{% url 'accounts:users' 'true' %}">{{active}}</a> </h6>
            </div>
          </div>
        </div>

      </div>
    </div><!-- End Revenue Card -->

    <div class="col-xxl-4 col-md-6">
      <div class="card info-card customers-card">

        <div class="card-body">
          <h5 class="card-title">In-Active Users</h5>

          <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
              <i class="bi bi-circle-fill"></i>
            </div>
            <div class="ps-3">
              <h6><a href="{% url 'accounts:users' 'false' %}">{{in_active}}</a> </h6>
            </div>
          </div>
        </div>

      </div>
    </div><!-- End Revenue Card -->
  </div>
  </div>
    <div class="col-lg-4">

      <!-- Recent Activity -->
      <div class="hrmis-scroll">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Board <span>|  {% now "jS F Y H:i" %}</span></h5>

          <div class="activity">
              {% for board in qs_board %}
            <div class="activity-item d-flex">
              <div class="activite-label" style="min-width: 0px;"></div>
              <i class="bi bi-circle-fill activity-badge text-success align-self-start"></i>
              <div class="activity-content">
                <a href="{% url 'boards:board_details' board.pk %}">{{board.title|title}}</a>
                <br>
                <small>Posted: {{board.timestamp|timesince}} ago</small>
               
              </div>
            </div><!-- End activity item-->
          {% endfor %}
          </div>

        </div>
      </div><!-- End Recent Activity -->
    </div>
    </div>

  </div>

{% endblock %}

hrmis/accounts/templates/employee_dash.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Employee Dash{% endblock %}
{% block pagetitle %}
Admin Dashboard
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item active">Employee Dashboard</li>
{% endblock %}
{% block css %}
<style>
  div.hrmis-scroll {
  height: 350px;
  overflow: scroll;
}
</style>
{% endblock %}
{% block content %}
<div class="row">
  {% if messages %}
  {% for message in messages %}
  <div class="col-md-12">
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
      </button>
      {{ message }}
  </div>
</div>
  {% endfor %}
  {% endif %}
  <div class="col-lg-8">
    <div class="row">
    <!-- Sales Card -->
    <div class="col-xxl-4 col-md-12">
      <div class="card info-card sales-card">

        <div class="card-body">
          <h5 class="card-title">Assigned Tasks</h5>
          <div class="d-flex align-items-center">
            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                <i class="bi bi-list-task"></i>
            </div>
            <div class="ps-3">
                <a href="{% url 'tasks:employee_tasks' request.user.pk %}"><h6>{{number_of_tasks}}</h6></a>
            </div>
          </div>
        </div>

      </div>
    </div><!-- End Sales Card -->

  </div>
  </div>
    <div class="col-lg-4">

      <!-- Recent Activity -->
      <div class="hrmis-scroll">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Board <span>|  {% now "jS F Y H:i" %}</span></h5>

          <div class="activity">
              {% for board in qs_board %}
            <div class="activity-item d-flex">
              <div class="activite-label" style="min-width: 0px;"></div>
              <i class="bi bi-circle-fill activity-badge text-success align-self-start"></i>
              <div class="activity-content">
                <a href="{% url 'boards:board_details' board.pk %}">{{board.title|title}}</a>
                <br>
                <small>Posted: {{board.timestamp|timesince}} ago</small>
               
              </div>
            </div><!-- End activity item-->
          {% endfor %}
          </div>

        </div>
      </div><!-- End Recent Activity -->
    </div>
    </div>

  </div>

{% endblock %}

hrmis/accounts/templates/profile.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Profile for {{obj.get_full_name|title}}
{% endblock %}
{% block pagetitle %}
{{obj.get_full_name|title}}
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item"><a href="{% url 'accounts:users' %}">Users</a></li>
<li class="breadcrumb-item active">
    Profile for {{obj.get_full_name|title}}
</li>
{% endblock %}
{% block content %}
<section class="section profile">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                </button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
      <div class="col-xl-4">

        <div class="card">
          <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

            <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
            <h2>{{obj.get_full_name|title}}</h2>
            <h3>{{obj.designation|title}}</h3>
            <p>Date Joined: {{obj.date_joined}}</p>
            {% if obj.is_employee %}
            <hr>
            <p><a href="{% url 'tasks:employee_tasks' obj.pk %}">Tasks</a></p>
            <p><a href="">Productivity</a></p>
            {% endif %}
       
          </div>
        </div>

      </div>

      <div class="col-xl-8">

        <div class="card">
          <div class="card-body pt-3">
            <!-- Bordered Tabs -->
            <ul class="nav nav-tabs nav-tabs-bordered" role="tablist">

              <li class="nav-item" role="presentation">
                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview" aria-selected="true" role="tab">Overview</button>
              </li>

              <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit" aria-selected="false" role="tab" tabindex="-1">Edit Profile</button>
              </li>

              <!-- <li class="nav-item" role="presentation">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings" aria-selected="false" role="tab" tabindex="-1">Settings</button>
              </li> -->
            {% if request.user.pk == obj.pk %}
            <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password" aria-selected="false" role="tab" tabindex="-1">Change Password</button>
            </li>
            {% endif %}

            </ul>
            <div class="tab-content pt-2">

              <div class="tab-pane fade profile-overview active show" id="profile-overview" role="tabpanel">
              
                <h5 class="card-title">Profile Details</h5>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label ">Full Name</div>
                  <div class="col-lg-9 col-md-8">{{obj.get_full_name|title}}</div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-4 label">Gender</div>
                    <div class="col-lg-9 col-md-8">{{obj.gender|title}}</div>
                  </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Designation</div>
                  <div class="col-lg-9 col-md-8">{{obj.designation|title}}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Phone Number</div>
                  <div class="col-lg-9 col-md-8">{{obj.phone_number}}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Email</div>
                  <div class="col-lg-9 col-md-8">{{obj.email}}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Address</div>
                  <div class="col-lg-9 col-md-8">{{obj.address}}</div>
                </div>

              </div>
              
              <div class="tab-pane fade profile-edit pt-3" id="profile-edit" role="tabpanel">

                <form action="{% url 'accounts:edit_profile_admin' obj.pk %}" method="POST">
                    {% csrf_token %}
                      <div class="row mb-3"> 
                        <div class="col-sm-12">
                            {{ form.username|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.phone_number|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.designation|as_crispy_field }}
                        </div>
                        <div class="col-sm-6">
                            {{ form.gender|as_crispy_field }}
                        </div>
                        <div class="col-sm-12">
                            {{ form.address|as_crispy_field }}
                        </div>
                      </div>
                
        
                      <div class="text-center">
                        <button type="submit" class="btn btn-primary">Update User Details</button>
        
                      </div>
                    </form><!-- End Horizontal Form -->

              </div>
             
              {% if request.user.pk == obj.pk %}
              <div class="tab-pane fade pt-3" id="profile-change-password" role="tabpanel">
                <!-- Change Password Form -->
                <form action="{% url 'accounts:change_password' obj.pk %}" method="POST">
                    {% csrf_token %}
                  <div class="row mb-3">
                    {{ form_change_password|crispy}}
                  </div>

                  <div class="text-center">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                  </div>
                </form><!-- End Change Password Form -->

              </div>
              {% endif %}

            </div><!-- End Bordered Tabs -->

          </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}

hrmis/accounts/templates/users.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Users{% endblock %}
{% block css %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
{% endblock %}
{% block pagetitle %}
Users
{% endblock %}
{% block breadcrum %}
<li class="breadcrumb-item active">Users</li>
{% endblock %}
{% block content %}
<section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'accounts:sign_up' %}">Add User</a>
              
                <!-- {% if not filter == None %}
                <a href="{% url 'accounts:users' %}">
                  remove 
                </a>
                {% endif %} -->
               
              </h5>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    </button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
            <hr>
            <!-- Default Table -->
            <table class="table" id="users">
              <thead>
                <tr>
                  
                  <th scope="col">Employee ID</th>
                  <th scope="col">Full Name</th>
                  <th scope="col">Designation</th>
                  <th scope="col">Date Joined</th>
                  <th scope="col">Active</th>
                </tr>
              </thead>
              <tbody>
                {% for user in obj %}
                <tr>  
                  <td><strong><a href="{% url 'accounts:profile' user.pk %}">{{user.username}}</a> </strong> </td>
                  <td>{{user.first_name|title}} {{user.last_name|title}}</td>
                  <td>{{user.designation|title}}</td>
                  <td>{{user.date_joined}}</td>
                  <td><a href="{% url 'accounts:toggle_user_status' user.pk %}">
                    {% if user.is_active %}
                    <i class="bi bi-circle-fill" style="color:green;"></i>
                    {% else %}
                    <i class="bi bi-circle-fill" style="color:red;"></i>
                    {% endif %}
                  </a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
        </div>

      </div>
    </div>
  </section>


{% endblock %}
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script>
$(document).ready(function () {
    $('#users').DataTable();
});
</script>
{% endblock %}